services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Car_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app


  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
