"""Fix problem with Appointment model

Revision ID: fff35bfe09e4
Revises: 4ce5a64626ba
Create Date: 2024-12-14 17:14:39.688532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff35bfe09e4'
down_revision: Union[str, None] = '4ce5a64626ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
